// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9_CGZ5vuT6Qj1vtXvzzHvhqZtcHdoljI',
    appId: '1:1026990396626:web:943f9cb38441d980adc90b',
    messagingSenderId: '1026990396626',
    projectId: 'testbar4',
    authDomain: 'testbar4.firebaseapp.com',
    storageBucket: 'testbar4.appspot.com',
    measurementId: 'G-F4ZTQQ3SGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_oCcHNI4ue9p1StzJSK9X_PvrjWi78tg',
    appId: '1:1026990396626:android:822a9dd016e83265adc90b',
    messagingSenderId: '1026990396626',
    projectId: 'testbar4',
    storageBucket: 'testbar4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU-9MBK9pe4GyTL-k8BCvdCEcvxbKJJn0',
    appId: '1:1026990396626:ios:89a45b83695353b9adc90b',
    messagingSenderId: '1026990396626',
    projectId: 'testbar4',
    storageBucket: 'testbar4.appspot.com',
    iosBundleId: 'com.example.testbar4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU-9MBK9pe4GyTL-k8BCvdCEcvxbKJJn0',
    appId: '1:1026990396626:ios:89a45b83695353b9adc90b',
    messagingSenderId: '1026990396626',
    projectId: 'testbar4',
    storageBucket: 'testbar4.appspot.com',
    iosBundleId: 'com.example.testbar4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9_CGZ5vuT6Qj1vtXvzzHvhqZtcHdoljI',
    appId: '1:1026990396626:web:dfb8f84085ab0b1aadc90b',
    messagingSenderId: '1026990396626',
    projectId: 'testbar4',
    authDomain: 'testbar4.firebaseapp.com',
    storageBucket: 'testbar4.appspot.com',
    measurementId: 'G-78F12B7JM6',
  );
}
